title: Security Engineer Blog
description: A simple blog built from scratch
author: Jay E
baseurl: "jay-e.dev"  # important for username.github.io
url: "https://jayjoe101.github.io"

# Jekyll settings
permalink: /:title/

# Future-proof
future: true