title: My Blog
description: A simple blog built from scratch
author: Jay E
baseurl: ""
url: "https://jay-e.dev"

permalink: /:title/

collections:
  blog:
    output: true
    permalink: /:title/
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"

future: true

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlighter-rouge'
    span:
      line_numbers: false