title: My Blog
description: A simple blog built from scratch
author: Jay E
baseurl: ""
url: "https://jay-e.dev"

# these are all Jekyll settings
# and allow me to have the custom setup im using
permalink: /:title/

collections:
  blog:
    output: true
    permalink: /:title/
  projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"

future: true